version: '3'

services: 
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm run dev
    environment: 
      - NODE_ENV=dev
    ports: 
      - 8080:8080
    volumes:
      - ./:/usr/app